#!/usr/bin/env python3
"""
Learning Archiver - 自動學習歸檔系統
自動將錯誤和經驗記錄到 Self-Improving 系統
"""

import os
import sys
import json
import re
from datetime import datetime
from pathlib import Path

# 路徑設定
HOME = Path.home()
LEARNINGS_DIR = HOME / ".openclaw" / "skills" / "self-improving" / ".learnings"
ERRORS_FILE = LEARNINGS_DIR / "ERRORS.md"
LEARNINGS_FILE = LEARNINGS_DIR / "LEARNINGS.md"
LOG_DIR = HOME / ".openclaw" / "skills" / "learning-archiver" / "logs"

# 確保目錄存在
LEARNINGS_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)


def log(message):
    """記錄日誌"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_file = LOG_DIR / f"{datetime.now().strftime('%Y-%m-%d')}.log"
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(f"{timestamp} - {message}\n")
    print(f"{timestamp} - {message}")


def detect_error_patterns(messages):
    """檢測錯誤模式"""
    error_indicators = [
        r"錯了|不對|應該是|不是這樣|搞錯|誤解",
        r"stop|delete|remove|cancel",
        r"失敗|error|failed|exception",
        r"唔該|請不要|千祈唔好",
    ]
    
    corrections = []
    for msg in messages:
        content = msg.get("content", "")
        for pattern in error_indicators:
            if re.search(pattern, content, re.IGNORECASE):
                corrections.append({
                    "timestamp": msg.get("timestamp"),
                    "content": content,
                    "pattern": pattern
                })
                break
    
    return corrections


def detect_learning_patterns(messages, tool_calls_count):
    """檢測學習模式"""
    learning_indicators = [
        r"記住|記得|以後要|下次|以後",
        r"做得好|正確|完美|成功",
        r"自動化|腳本|效率|優化",
    ]
    
    learnings = []
    
    # 條件 1: 用戶明確表示記住
    for msg in messages:
        content = msg.get("content", "")
        for pattern in learning_indicators:
            if re.search(pattern, content, re.IGNORECASE):
                learnings.append({
                    "type": "explicit",
                    "timestamp": msg.get("timestamp"),
                    "content": content
                })
                break
    
    # 條件 2: 複雜任務成功完成
    if tool_calls_count > 5:
        # 檢查最後是否成功
        last_msg = messages[-1] if messages else None
        if last_msg and not any(x in last_msg.get("content", "") for x in ["錯", "fail", "error"]):
            learnings.append({
                "type": "complex_task",
                "tool_calls": tool_calls_count,
                "timestamp": last_msg.get("timestamp")
            })
    
    return learnings


def format_error_entry(error_info, session_summary):
    """格式化錯誤條目"""
    date_str = datetime.now().strftime("%Y-%m-%d")
    
    # 提取錯誤描述
    error_desc = error_info.get("content", "Unknown error")[:200]
    
    entry = f"""## {date_str} - {error_desc[:50]}...

**錯誤描述**: {error_desc}
**影響**: 用戶體驗、任務完成
**糾正措施**: 用戶已糾正
**預防方案**: 
1. 仔細理解指令
2. 高風險操作先確認
3. 參考過往錯誤記錄

**參考**: Session 相關對話

---

"""
    return entry


def format_learning_entry(learning_info, session_summary):
    """格式化經驗條目"""
    date_str = datetime.now().strftime("%Y-%m-%d")
    
    if learning_info.get("type") == "complex_task":
        entry = f"""## {date_str} - 複雜任務成功完成

**情境**: 任務涉及 {learning_info.get('tool_calls', '多個')} 個工具調用
**做法**: 系統化執行、逐步驗證
**效果**: 成功完成
**可重用性**: 高

---

"""
    else:
        content = learning_info.get("content", "")[:200]
        entry = f"""## {date_str} - {content[:50]}...

**情境**: 用戶明確指示
**做法**: {content}
**效果**: 待觀察
**可重用性**: 中

---

"""
    
    return entry


def append_to_file(filepath, content):
    """追加內容到檔案"""
    filepath = Path(filepath)
    
    # 如果檔案不存在，創建標題
    if not filepath.exists():
        title = "# Error Log" if "ERRORS" in filepath.name else "# Learnings Log"
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(f"{title}\n\n> Auto-generated by Learning Archiver\n\n")
    
    # 追加內容
    with open(filepath, "a", encoding="utf-8") as f:
        f.write(content)
    
    log(f"Appended to {filepath}")


def archive_session(session_data):
    """歸檔單個會話"""
    messages = session_data.get("messages", [])
    tool_calls = session_data.get("tool_calls", [])
    
    if not messages:
        log("No messages to archive")
        return
    
    log(f"Processing session with {len(messages)} messages, {len(tool_calls)} tool calls")
    
    # 檢測錯誤
    errors = detect_error_patterns(messages)
    if errors:
        log(f"Detected {len(errors)} error patterns")
        for error in errors[:3]:  # 最多記錄 3 個
            entry = format_error_entry(error, session_data)
            append_to_file(ERRORS_FILE, entry)
    
    # 檢測學習點
    learnings = detect_learning_patterns(messages, len(tool_calls))
    if learnings:
        log(f"Detected {len(learnings)} learning patterns")
        for learning in learnings[:3]:  # 最多記錄 3 個
            entry = format_learning_entry(learning, session_data)
            append_to_file(LEARNINGS_FILE, entry)
    
    if not errors and not learnings:
        log("No patterns detected")


def main():
    """主函數"""
    log("Learning Archiver started")
    
    # 讀取輸入 (從 stdin 或檔案)
    if len(sys.argv) > 1:
        # 從檔案讀取
        input_file = sys.argv[1]
        with open(input_file, "r", encoding="utf-8") as f:
            session_data = json.load(f)
    else:
        # 從 stdin 讀取
        try:
            session_data = json.load(sys.stdin)
        except json.JSONDecodeError:
            log("No valid input provided")
            return
    
    # 執行歸檔
    archive_session(session_data)
    
    log("Learning Archiver completed")


if __name__ == "__main__":
    main()
