# TQQQ Trend-MeanReversion Hybrid Strategy
# 趨勢+均值回歸混合策略參數配置

# 核心參數
ZSCORE_LOOKBACK = 30  # Z-Score回看週期
ZSCORE_LONG_THRESHOLD = -2.2  # 做多閾值
ZSCORE_SHORT_THRESHOLD = 2.5  # 做空閾值

# 趨勢判斷參數
EMA_SHORT = 20
EMA_LONG = 50
ADX_THRESHOLD = 25

# RSI參數
RSI_PERIOD = 14
RSI_LONG_MAX = 40
RSI_SHORT_MIN = 60

# 風險管理參數
POSITION_SIZE_PCT = 0.20  # 單筆倉位 20%
POSITION_SIZE_SHORT_MAX = 0.25  # 做空最大倉位 25%
RISK_PER_TRADE_PCT = 0.01  # 單筆風險 1%

# 止損止盈參數
STOP_LOSS_ATR_MULT_LONG = 1.5
STOP_LOSS_ATR_MULT_SHORT = 2.0
TRAILING_STOP_ATR_MULT = 3.0
TIME_STOP_DAYS = 10

# 熔斷機制
CIRCUIT_BREAKER_WARNING = 0.05  # 5% 警告
CIRCUIT_BREAKER_LIMIT = 0.10    # 10% 限制
CIRCUIT_BREAKER_HALT = 0.15     # 15% 熔斷

# VIX過濾
VIX_THRESHOLD = 25
VIX_POSITION_REDUCTION = 0.50  # VIX>25時減倉50%

# 季節性過濾
AVOID_MONTHS = [9]  # 避免9月交易
PREFERRED_WEEKDAYS = [0, 1, 2]  # 週一、二、三 (0=Monday)

# 波動率過濾
VOLATILITY_PERCENTILE_THRESHOLD = 75  # 20日波動率75%分位數

# 連續虧損處理
CONSECUTIVE_LOSSES_REDUCE = 3
CONSECUTIVE_LOSSES_HALT = 5
HALT_DURATION_HOURS = 24

# 交易時間
MARKET_OPEN_HOUR = 9
MARKET_OPEN_MINUTE = 30
MARKET_CLOSE_HOUR = 16
MARKET_CLOSE_MINUTE = 0
