-- Create decisions table
CREATE TABLE IF NOT EXISTS decisions (
    id SERIAL PRIMARY KEY,
    absolute_score INTEGER,
    reference_score INTEGER,
    final_score DECIMAL(5,2),
    signal VARCHAR(10) CHECK (signal IN ('BUY', 'SELL', 'HOLD')),
    risk_check_passed BOOLEAN,
    error_flag BOOLEAN DEFAULT FALSE,
    error_message TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_decisions_timestamp ON decisions(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_decisions_signal ON decisions(signal);

COMMENT ON TABLE decisions IS 'Trading decisions generated by the decision engine';
COMMENT ON COLUMN decisions.absolute_score IS 'Absolute trend score (0-100)';
COMMENT ON COLUMN decisions.reference_score IS 'Reference composite score (0-100)';
COMMENT ON COLUMN decisions.final_score IS 'Weighted final score (absolute*0.6 + reference*0.4)';
COMMENT ON COLUMN decisions.signal IS 'Trading signal: BUY, SELL, or HOLD';
COMMENT ON COLUMN decisions.risk_check_passed IS 'Whether risk management checks passed';
COMMENT ON COLUMN decisions.error_flag IS 'Whether an error occurred during decision making';